// <auto-generated />
using System;
using ExamApp.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamApp.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    partial class ExamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamApp.Domain.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("duration");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("ExamApp.Domain.Exam", b =>
                {
                    b.OwnsMany("ExamApp.Domain.ExamQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int?>("CorrectAnswer")
                                .HasColumnType("integer")
                                .HasColumnName("correct_answer");

                            b1.Property<Guid>("ExamId")
                                .HasColumnType("uuid")
                                .HasColumnName("exam_id");

                            b1.Property<int>("Index")
                                .HasColumnType("integer")
                                .HasColumnName("index");

                            b1.Property<int>("SourceQuestionId")
                                .HasColumnType("integer")
                                .HasColumnName("source_question_id");

                            b1.Property<int?>("UserSelection")
                                .HasColumnType("integer")
                                .HasColumnName("user_selection");

                            b1.Property<string>("answerOrder")
                                .HasColumnType("jsonb")
                                .HasColumnName("answer_order");

                            b1.Property<string>("explanations")
                                .HasColumnType("jsonb")
                                .HasColumnName("explanations");

                            b1.HasKey("Id")
                                .HasName("pk_exam_question");

                            b1.HasIndex("ExamId")
                                .HasDatabaseName("ix_exam_question_exam_id");

                            b1.ToTable("exam_question", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExamId")
                                .HasConstraintName("fk_exam_question_exams_exam_id");
                        });

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
